import { z } from 'zod';

export const configWeb = z.object({
  id: z.number().int().positive(),
  judul_web: z.string().min(1),
  deskripsi_web: z.string().min(1),
  keyword: z.string().min(1),
  og_image: z.string().nullable(),
  logo_header: z.string().nullable(),
  logo_footer: z.string().nullable(),
  logo_favicon: z.string().nullable(),
  logo_banner: z.string().nullable(),
  logo_cs: z.string().nullable(),
  url_wa: z.string().url(),
  url_ig: z.string().url(),
  url_tiktok: z.string().url(),
  url_youtube: z.string().url(),
  url_fb: z.string().url(),
  kbrstore_api: z.string().min(1),
  slogan_web: z.string().min(1),
  snk: z.string().min(1),
  privacy: z.string().min(1),
  warna1: z.string().min(1),
  warna2: z.string().min(1),
  warna3: z.string().min(1),
  warna4: z.string().min(1),
  warna5: z.string().min(1),
  harga_gold: z.string().min(1),
  harga_platinum: z.string().min(1),
  tripay_api: z.string().nullable(),
  tripay_merchant_code: z.string().nullable(),
  tripay_private_key: z.string().nullable(),
  duitku_key: z.string().nullable(),
  duitku_merchant: z.string().nullable(),
  username_digi: z.string().nullable(),
  api_key_digi: z.string().nullable(),
  apigames_secret: z.string().nullable(),
  apigames_merchant: z.string().nullable(),
  vip_apiid: z.string().nullable(),
  vip_apikey: z.string().nullable(),
  digi_seller_user: z.string().nullable(),
  digi_seller_key: z.string().nullable(),
  nomor_admin: z.string().nullable(),
  wa_key: z.string().nullable(),
  wa_number: z.string().nullable(),
  ovo_admin: z.string().nullable(),
  ovo1_admin: z.string().nullable(),
  gopay_admin: z.string().nullable(),
  gopay1_admin: z.string().nullable(),
  dana_admin: z.string().nullable(),
  shopeepay_admin: z.string().nullable(),
  bca_admin: z.string().nullable(),
  mandiri_admin: z.string().nullable(),
  logo_ceo: z.string().nullable(),
  sejarah: z.string().min(1),
  sejarah_1: z.string().min(1),
  visi: z.string().min(1),
  misi: z.string().min(1),
  nama_ceo: z.string().min(1),
  deskripsi_ceo: z.string().min(1),
  nama_bagan: z.string().min(1),
  alamat: z.string().min(1),
  telp: z.string().min(1),
  email: z.string().email(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  waPending   :z.string().nullable(),   
  waPaid    :z.string().nullable(),  
  waProcess  :z.string().nullable(),  
  waSuccess  :z.string().nullable(),  
});

export type CreateConfigWeb = z.infer<typeof configWeb>;
export type UpdateConfigWeb = Partial<CreateConfigWeb>;
export type ConfigWeb = CreateConfigWeb & {
  created_at: string;
  updated_at: string;
};
